version: 0.2

phases:

  install:
    commands:
      - "apt-get install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/0.14.2/terraform_0.14.2_linux_amd64.zip"
      - "unzip terraform_0.14.2_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo terraform apply completed
