version: 0.2

phases:

  install:
    commands:
      - "apt-get install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/0.14.4/terraform_0.14.4_linux_amd64.zip"
      - "unzip terraform_0.14.4_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - sed -i.1 's/BUCKET/'"$TF_BUCKET"'/g' main.tf
      - sed -i.2 's/TABLE/'"$TF_TABLE"'/g' main.tf 
      - terraform init

  build:
    commands:
      - terraform $TF_COMMAND -auto-approve 

  post_build:
    commands:
      - echo 'terraform '"$TF_COMMAND"' completed'
